services:
  artef_dev:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile.dev
    volumes:
      - ..:/workspace:cached
      - artef_cache:/home/node/.artef/
      - artef_npm_global:/home/node/.npm-global
    command: sleep infinity

volumes:
  artef_cache:
  artef_npm_global:
